### ISSUE TITLE
Error running check

### ISSUE THREAD

**Issue by stovenator** [glg-public/gds-cc-screamer#184]
We are going to remove the templates.json, since there are not client-side EPI calls, but wanted to bring this bug to your attention.

```
Error
    at /home/runner/work/_actions/glg-public/gds-cc-screamer/main/checks/valid-templates-json.js:220:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 5)
    at async validTemplatesJson (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/checks/valid-templates-json.js:142:5)
    at async run (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/index.js:192:21)
```

**Comment by dhunt787** [comment]
@stovenator PR to remove the templates [here](https://github.com/glg/gds.clusterconfig.s01/pull/511)
