### ISSUE TITLE
Error while posting comment

### ISSUE THREAD

**Issue by rauhryan** [glg-public/gds-cc-screamer#225]
```
Cannot read properties of undefined (reading 'hasOwnProperty')

TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at leaveComment (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/util/github.js:96:19)
    at run (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/index.js:218:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by rauhryan** [comment]
context: https://github.com/glg/gds.clusterconfig.s07/pull/23
