### ISSUE TITLE
Error Running Check Suite

### ISSUE THREAD

**Issue by JohnLemberger** [glg-public/gds-cc-screamer#46]
```
Cannot read property 'hasOwnProperty' of undefined

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at lineLink (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/util/github.js:209:10)
    at leaveComment (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/util/github.js:74:31)
    at run (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/index.js:116:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by JohnLemberger** [comment]
This just happened again in `https://github.com/glg/gds.clusterconfig.p01/pull/31`
