### ISSUE TITLE
Error Running Check Suite ?

### ISSUE THREAD

**Issue by fearphage** [glg-public/gds-cc-screamer#62]
This was the result of committing a suggestion of the comment on the scheduled jobs.

```
Not Found

HttpError: Not Found
    at /home/runner/work/_actions/glg-public/gds-cc-screamer/main/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async clearPreviousRunComments (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/util/github.js:311:5)
    at async run (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/index.js:65:5)
```

**Comment by shawnrushefsky** [comment]
This happens when the check suite tries to delete a comment that has already been deleted. I need to check for that specific error and ignore it instead of throwing
